language: scala
jdk: openjdk8
git:
  depth: 10

scala:
  - 2.11.12
  - 2.12.10

env:
  matrix:
    - version=33
    - version=34
    - version=35
    - version=36

script:
  - sbt "++$TRAVIS_SCALA_VERSION" "nitf${version}/test"
  - sbt "++$TRAVIS_SCALA_VERSION" "nitf${version}/doc"

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Clean up the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
