language: scala
jdk: oraclejdk8
scala:
  - 2.11.12
  - 2.12.4
git:
  depth: 1

env:
  matrix:
    - version=33
    - version=34
    - version=35
    - version=36

script:
  - sbt "++$TRAVIS_SCALA_VERSION" "nitf${version}Test/test" "nitf${version}Builders/test"

# These directories are cached to S3 at the end of the build
cache:
  timeout: 86400
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
